* Helm/Ivy/?

Here is the old section from the tutorial. Removed it as helm/ivy is a
choice that will depend on customization.

 HELM
-------

Helm is a very useful package. Boon provides special support for it.

>> If you have not done it yet, install helm now: (package-install 'helm)

The command '\\[helm-occur]' starts `helm-occur'; which does a quick search for all
occurrences of a pattern in the current buffer.

>> Type '\\[helm-occur]' now

>> Within the helm prompt area, type 'helm <return>' to jump to
   the beginning of this section.

You can search for the current symbol by typing SPC in an empty
helm mini-buffer.

>> Move the cursor to an occurrence of the helm word, and type '\\[helm-occur] SPC'.

\\<boon-helm-command-map>
>> Use C-\\[helm-previous-line] and C-\\[helm-next-line] to select an occurrence, then type <return> to jump to
   the currently selected occurrence

Note: after typing \\<helm-map>\\[helm-previous-line], it
suffices to type \\<helm-map>\\[helm-previous-line] to perform
`helm-previous-line'.
The keys which do not require repeating the C- prefix are:
\\{boon-helm-command-map}
\\<boon-command-map>


Besides `helm-occur', a few other helm commands are bound to keys starting with the same prefix:

\\[helm-apropos] --> `helm-apropos'
\\[helm-resume] --> `helm-resume'
\\[helm-show-kill-ring] --> `helm-show-kill-ring'

The full list of key bound to that prefix is:
\\{boon-goto-map}

* Fully Support Fundamental buffers
I tried to do this following the code in Evil but it does not work.

According to Sefan Monnier (private email), creating a buffer without
setting up the "fundamental mode" is not allowed. So there is nothing
to do except bug the maintainers of the offending packages.


